### ISSUE TITLE
File not Found.!

### ISSUE THREAD

**Issue by StanlyBabu** [DebadityaPal/RoBERTa-NL2SQL#3]
I was running the code through Colab but have faced a FileNotFoundError. Can you please help me with the issue. Below is the error message from colab.

`FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-6-8cd259bf5453>](https://localhost:8080/#) in <module>()
      6 
      7 train_data, train_table, dev_data, dev_table, train_loader, dev_loader = load_data.get_data(path_wikisql, batch_size = BATCH_SIZE)
----> 8 test_data,test_table,test_loader = load_data.get_test_data(path_wikisql, batch_size = BATCH_SIZE)
      9 zero_data,zero_table,zero_loader = load_data.get_zero_data(path_wikisql, batch_size = BATCH_SIZE)    # Data to test Zero Shot Learning

[/content/RoBERTa-NL2SQL/load_data.py](https://localhost:8080/#) in get_test_data(file_path, batch_size)
     71     test_table = {}
     72 
---> 73     with open(file_path + '/test_knowledge.jsonl') as test_data_file:
     74         for idx, line in enumerate(test_data_file):
     75             current_line = json.loads(line.strip())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/NL2SQL/test_knowledge.jsonl'`

**Comment by DebadityaPal** [comment]
Did you do the first step in the Readme file?

**Comment by DebadityaPal** [comment]
Somehow the file got deleted. I added it again. It should work now.
Feel free to reopen the issue if it doesn't work

**Comment by StanlyBabu** [comment]
I do not find the file in the drive link. Can you please check once @DebadityaPal .

**Comment by DebadityaPal** [comment]
So a lot of the files got deleted in a drive cleanup. I restored the data files. But the model checkpoints are gone unfortunately. I'm retraining the models and will save them, but it might take some time.

The scripts will work, but if you want to use the model, unfortunately you have to train it yourself for now.

**Comment by StanlyBabu** [comment]
Can you help me with the code for generating the test_knowlwdge file using the database table. So that I can work on different test sets.

**Comment by DebadityaPal** [comment]
I will help you with that, just give me a few days. I just got back to
India from an internship in the states so I'm just trying to get back on
track. I'll send you the code within a few days.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
07/19/22,
12:38:31 PM

**Comment by StanlyBabu** [comment]
Thank you. Does the model work for multiple columns retrieval.
Ex: SELECT ID,Name FROM Students WHERE Marks>90;
for a sentence "Display id and names of students who got marks above 90?".

**Comment by DebadityaPal** [comment]
The model cannot retrieve multiple columns.  That is a drawback, we even mentioned that in the future scope of our paper.

**Comment by DebadityaPal** [comment]
This colab contains the code to preprocess. 
[https://colab.research.google.com/drive/1QqD_zrbu6qa4BwmS2hv-si-Wbh-iCQJk?usp=sharing](https://colab.research.google.com/drive/1QqD_zrbu6qa4BwmS2hv-si-Wbh-iCQJk?usp=sharing)

You need the tables file and the query files to create the knowledge file which is what the model uses.

**Comment by StanlyBabu** [comment]
Thank you for your kind support in helping me to solve my issues.

**Comment by DebadityaPal** [comment]
No worries. Are you able to access the colab notebook?

**Comment by StanlyBabu** [comment]
Yes. Thank you. Is Seq2Sql approach better or Roberta?

**Comment by DebadityaPal** [comment]
We found RoBERTa to be better.
